/**
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package foo

import goo.wee


function void goo1() {
	//do something ! { yeah }
}

function String goo2(String la) {
	//yeah man !
	return "whee";
}

function String goo3() { return "HELLO"; }

function String goo4() { 

	if( true ) {
		return "HELLO"; 
	}
}

/*
	function String goo5() { 
	
		if( true ) {
			return "HELLO"; 
		}
	}
*/

function String goo6() { 

		return "HELLO"; 
	/* } */
	/* }
	}
	} */
}

rule "blah"
 when
   Whee()
 then
   goo();
end


rule "cha"
  when
   Sup()
  then
   ka();
end