function org_drools_guvnor_Guvnor(){var l='',B='" for "gwt:onLoadErrorFn"',z='" for "gwt:onPropertyErrorFn"',cc='"><\/script>',n='/',jb='4FB1880E1735BEB2EC5B4F545F090697.cache.html',ib='7290F864B4A95C90564D34A3F952C091.cache.html',kb='998371C8029A5B4A7E965E722352FF4C.cache.html',bc='<script id="',Bb='<script language="javascript" src="',Fb="<script>org_drools_guvnor_Guvnor.onInjectionDone('org.drools.guvnor.Guvnor')<\/script>",v='=',y='Bad handler "',lb='C1846CBED9789002F02A2D2D413AEEC8.cache.html',mb='DBF9FB4F9056517D08BECFD78178FD35.cache.html',vb='DOMContentLoaded',ob='GwtExt.css',dc='SCRIPT',ac='__gwt_marker_org.drools.guvnor.Guvnor',o='base',q='clear.cache.gif',u='content',db='gecko',eb='gecko1_8',nb='gwt.hybrid',A='gwt:onLoadErrorFn',w='gwt:onPropertyErrorFn',t='gwt:property',tb='head',hb='hosted.html?org_drools_guvnor_Guvnor',sb='href',bb='ie6',wb='iframe',p='img',xb="javascript:''",Ab='js/ext/adapter/ext/ext-base.js',Cb='js/ext/adapter/ext/ext-base.js"><\/script>',Db='js/ext/ext-all.js',Eb='js/ext/ext-all.js"><\/script>',ub='js/ext/resources/css/ext-all.css',pb='link',r='meta',gb='moduleRequested',ab='msie',s='name',D='opera',m='org.drools.guvnor.Guvnor',zb='position:absolute;width:0;height:0;border:none',qb='rel',F='safari',yb='selectionDone',cb='selectionStart',x='startup',rb='stylesheet',fb='unknown',C='user.agent',E='webkit';var fc=window,k=document,nc=fc.external,ec=fc.__gwtstatsEvent?function(a,b,c,d){fc.__gwtstatsEvent(a,b,c,d)}:null,Ac,qc,kc,jc=l,tc={},Dc=[],zc=[],ic=[],wc,yc;ec&&ec(m,x,cb,{millis:(new Date()).getTime()});if(!fc.__gwt_stylesLoaded){fc.__gwt_stylesLoaded={}}if(!fc.__gwt_scriptsLoaded){fc.__gwt_scriptsLoaded={}}function pc(){try{return nc&&(nc.gwtOnLoad&&fc.location.search.indexOf(nb)==-1)}catch(a){return false}}
function sc(){if(Ac&&qc){var c=k.getElementById(m);var b=c.contentWindow;b.__gwt_initHandlers=org_drools_guvnor_Guvnor.__gwt_initHandlers;if(pc()){b.__gwt_getProperty=function(a){return lc(a)}}org_drools_guvnor_Guvnor=null;b.gwtOnLoad(wc,m,jc);ec&&ec(m,x,yb,{millis:(new Date()).getTime()})}}
function mc(){var j,h=ac,i;k.write(bc+h+cc);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=dc){j=j.previousSibling}function d(b){var a=b.lastIndexOf(n);return a>=0?b.substring(0,a+1):l}
;if(j&&j.src){jc=d(j.src)}if(jc==l){var c=k.getElementsByTagName(o);if(c.length>0){jc=c[c.length-1].href}else{var g=k.location;var e=g.href;jc=d(e.substr(0,e.length-g.hash.length))}}else if(jc.match(/^\w+:\/\//)){}else{var f=k.createElement(p);f.src=jc+q;jc=d(f.src)}if(i){i.parentNode.removeChild(i)}}
function xc(){var f=document.getElementsByTagName(r);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(s),b;if(h){if(h==t){b=e.getAttribute(u);if(b){var i,c=b.indexOf(v);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}tc[h]=i}}else if(h==w){b=e.getAttribute(u);if(b){try{yc=eval(b)}catch(a){alert(y+b+z)}}}else if(h==A){b=e.getAttribute(u);if(b){try{wc=eval(b)}catch(a){alert(y+b+B)}}}}}}
function Cc(d,e){var a=ic;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function lc(d){var e=zc[d](),b=Dc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(yc){yc(d,a,e)}throw null}
zc[C]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(D)!=-1){return D}else if(d.indexOf(E)!=-1){return F}else if(d.indexOf(ab)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return bb}}}else if(d.indexOf(db)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return eb}return db}return fb};Dc[C]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};org_drools_guvnor_Guvnor.onInjectionDone=function(){Ac=true;ec&&ec(m,x,gb,{millis:(new Date()).getTime()});sc()};org_drools_guvnor_Guvnor.onScriptLoad=function(){if(oc){qc=true;sc()}};mc();xc();var Bc;if(pc()){Bc=hb}else{try{Cc([D],ib);Cc([F],jb);Cc([db],kb);Cc([eb],lb);Cc([bb],mb);Bc=ic[lc(C)]}catch(a){return}}var vc;function uc(){if(!kc){kc=true;if(!__gwt_stylesLoaded[ob]){var a=k.createElement(pb);__gwt_stylesLoaded[ob]=a;a.setAttribute(qb,rb);a.setAttribute(sb,jc+ob);k.getElementsByTagName(tb)[0].appendChild(a)}if(!__gwt_stylesLoaded[ub]){var a=k.createElement(pb);__gwt_stylesLoaded[ub]=a;a.setAttribute(qb,rb);a.setAttribute(sb,jc+ub);k.getElementsByTagName(tb)[0].appendChild(a)}sc();if(k.removeEventListener){k.removeEventListener(vb,uc,false)}if(vc){clearInterval(vc)}}}
var oc;function rc(){if(!oc){oc=true;var a=k.createElement(wb);a.src=xb;a.id=m;a.style.cssText=zb;a.tabIndex=-1;k.body.appendChild(a);a.contentWindow.location.replace(jc+Bc)}}
if(k.addEventListener){k.addEventListener(vb,function(){rc();uc()},false)}var vc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){rc();uc()}},50);if(!__gwt_scriptsLoaded[Ab]){__gwt_scriptsLoaded[Ab]=true;document.write(Bb+jc+Cb)}if(!__gwt_scriptsLoaded[Db]){__gwt_scriptsLoaded[Db]=true;document.write(Bb+jc+Eb)}k.write(Fb)}
org_drools_guvnor_Guvnor.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i()}finally{g&&g(a)}};d.onbeforeunload=function(a){var c,b;try{c=e()}finally{b=f&&f(a)}if(c!=null){return c}if(b!=null){return b}};d.onunload=function(a){try{j()}finally{h&&h(a)}}};org_drools_guvnor_Guvnor();