package permissions.zone2

import org.jboss.drools.guvnor.importgenerator.example.domain.RuleResultVO;
import org.jboss.drools.guvnor.importgenerator.example.domain.PermissionVO;
import org.jboss.drools.guvnor.importgenerator.example.domain.UserVO;

rule "does the user have permission to access zone 2"
when
	!RuleResult()
    $user: UserVO($permissions : permissions)
    eval($permissions.contains(new PermissionVO("ZONE_2")))
then
	insert(new RuleResultVO("success"));
end